version: '3'

services:
    mailcatcher:
        container_name: mailcatcher
        image: schickling/mailcatcher
        ports:
        - 1080:1080
        - 1025:1025

    mongo:
        container_name: mongo
        image: mongo:3.4
        volumes:
            - ./data/db:/data/db:cached
        ports:
            - 27017:27017

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.7-management
        ports:
            - 5671:5671
            - 5672:5672
            - 15672:15672

    redis:
        image: redis:3.2
        container_name: redis
        volumes:
            - ./db/storage/cache:/data:cached
        ports:
            - 6379:6379
